apiVersion: v1
data:
  # language=html
  index.html: |-
    <html lang="en">
      <head>
       <title>k3s in lxc</title>
       <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
      </head>
      <body>
       <div class="container">
        <div class="jumbotron">
         <div class="page-header"><h1>Hi from LXC</h1></div>
         <h3>You are running kubernetes via <a href="https://github.com/rancher/k3s">rancher/k3s</a></h3>
        </div>
       </div>
      </body>
    </html>
kind: ConfigMap
metadata:
  name: index-html

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-app
  name: test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
      - image: nginx
        imagePullPolicy: IfNotPresent
        name: nginx
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        volumeMounts:
        - mountPath: /usr/share/nginx/html/
          name: index-html
      terminationGracePeriodSeconds: 2
      volumes:
      - configMap:
          defaultMode: 420
          name: index-html
        name: index-html

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-app
  name: test-app
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: test-app
  type: ClusterIP

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app: example
  name: test-app
spec:
  rules:
  - host: k3s-lxc
    http:
      paths:
      - backend:
          serviceName: test-app
          servicePort: http
        path: /
